spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdata
    username: root
    password: 20141026
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 10
    maxActive: 100
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8


server:
  port: 5555
#整合mybatis
mybatis:
  type-aliases-package: com.blog.jxhj.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

